development:
  adapter: postgresql
  encoding: utf8
  pool: 5
  database: <%= ENV['DBDATABASE'] %>
  username: <%= ENV['DBUSERNAME'] %>
  password: <%= ENV['DBPASSWORD'] %>
  host: <%= ENV['DBHOST'] %>
  port: 5432
  timeout: 5000

test:
  adapter: postgresql
  encoding: utf8
  pool: 5
  database: <%= ENV['DBDATABASE'] %>
  username: <%= ENV['DBUSERNAME'] %>
  password: <%= ENV['DBPASSWORD'] %>
  host: <%= ENV['DBHOST'] %>
  port: 5432
  stimeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  pool: 5
  database: <%= ENV['DBDATABASE'] %>
  username: <%= ENV['DBUSERNAME'] %>
  password: <%= ENV['DBPASSWORD'] %>
  host: <%= ENV['DBHOST'] %>
  port: 5432
  timeout: 5000
