default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  user: <%= ENV['DBUSERNAME'] %>
  password: <%= ENV['DBPASSWORD'] %>
  port: 5432
  host: <%= ENV['DBHOST'] %>

development:
  <<: *default
  database: <%= ENV['DBDATABASE'] %>

test:
  <<: *default
  database: <%= ENV['DBDATABASE'] %>

production:
  <<: *default
  database: <%= ENV['DBDATABASE'] %>
