development:
  clients:
    default:
      database: <%= ENV['DBMONGODATABASE'] %>
      hosts:
        - <%= ENV['DBMONGOHOST'] %>
      options:
        user: <%= ENV['DBMONGOUSER'] %>
        password: <%= ENV['DBMONGOPASSWORD'] %>
  options:
test:
  clients:
    default:
      database: <%= ENV['DBMONGODATABASE'] %>
      hosts:
        - <%= ENV['DBMONGOHOST'] %>
      options:
        read:
          mode: primary
        max_pool_size: 1
